theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
