[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = "$title |"

[[block]]
block = "music"
format = "{ $icon $combo.str(max_w:20) $play $next |}"
interface_name_exclude = ["playerctld", "firefox"]

[[block]]
block = "cpu"
format = " $icon $barchart $utilization "

[[block]]
block = "memory"
format = " $icon RAM: $mem_used.eng(hide_unit:true, hide_prefix:true, w:1)/$mem_total.eng(p:Mi)"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "sound"
device_kind = "sink"
[[block.click]]
button = "left"
cmd = "pwvucontrol"

[[block]]
block = "sound"
device_kind = "source"
[[block.click]]
button = "left"
cmd = "pwvucontrol"

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""

[[block]]
icons_format = "<span color='#FF0000'>{icon}</span>"
block = "privacy"
[[block.driver]]
name = "pipewire"
display = "nickname"
[[block.driver]]
name = "v4l"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a, %d.%m.%Y %H:%M') "
